// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetMemoryUsage():Promise<string>;

export function IsConnected():Promise<boolean>;

export function SendMessage(arg1:string):Promise<void>;
